### ISSUE TITLE
Any options to define SSL cipher suites for cluster-agent?

### ISSUE THREAD

**Issue by ryanwong00** [canonical/microk8s-cluster-agent#39]
Hi all,

I am using a MicroK8s 1.27 cluster.  We recently used Nexsus to do a security scan and it raised a medium threat for 'SSL Medium Strength Cipher Suites Supported (SWEET32)' on port 25000.  Is there any way to define the cipher suite in cluster-agent?

Thanks in advance
Ryan

**Comment by ryanwong00** [comment]
Not sure if it's the proper way.  I have disabled the TLS1.2 by setting '--min-tls-version "tls13"' in /var/snap/microk8s/current/args/cluster-agent.  Seems like working since TLS 1.3 does not support 3DES encryption

**Comment by neoaggelos** [comment]
Hi @ryanwong00, thanks for raising this. Indeed, since 1.25 with https://github.com/canonical/microk8s-cluster-agent/pull/30 it is possible to specify `--min-tls-version`, the default being `tls12` (see https://github.com/canonical/microk8s-cluster-agent/pull/30/files#diff-03fa4cd0707409a739cef0e1cee7789c1e8fb3b28f9e2585e22d3a86a5fb2feeR124)

The default is currently `tls12` to ensure both backwards-compatibility as well as safety with older hardware/firmware, which is common in edge environments which we are interested in. Upgrading to `tls13` has been considered but will probably be some time before it is done.

Finally, note that since MicroK8s 1.27 [you can use launch configurations](https://microk8s.io/docs/add-launch-config) to specify this flag during MicroK8s installation, the config would look like this:

```yaml
---
version: 0.1.0
extraClusterAgentArgs:
  --min-tls-version: tls13
```

To verify, does adding `--min-tls-version tls13` in `/var/snap/microk8s/current/args/cluster-agent` make the security scanner happy?

**Comment by ryanwong00** [comment]
@neoaggelos , Thanks for your prompt reply.  I think adding the --min-tls-version to cluster-agent configuration should be fine.  It can be proved by using command 'nmap --script ssl-enum-ciphers -p 25000 hostname'.  The result showed that no more weak ciphers. 

> Starting Nmap 7.93 ( https://nmap.org ) at 2023-07-21 16:57 HKT
> Nmap scan report for xxxxxx (127.0.1.1)
> Host is up (0.00046s latency).
> 
> PORT      STATE SERVICE
> 25000/tcp open  icl-twobase1
> | ssl-enum-ciphers:
> |   TLSv1.3:
> |     ciphers:
> |       TLS_AKE_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
> |       TLS_AKE_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
> |       TLS_AKE_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
> |     cipher preference: server
> |_  least strength: A
> 
> Nmap done: 1 IP address (1 host up) scanned in 0.54 seconds

I am closing the issue.
